export  const   VALIDAR_FORMULARIO  =   'VALIDAR_FORMULARIO';
export  const   VALIDAR_FORMULARIO_EXITO  =   'VALIDAR_FORMULARIO_EXITO';
export  const   VALIDAR_FORMULARIO_ERROR  =   'VALIDAR_FORMULARIO_ERROR';