export  const   VALIDAR_FORMULARIO  =   'VALIDAR_FORMULARIO';
export  const   VALIDAR_FORMULARIO_EXITO  =   'VALIDAR_FORMULARIO_EXITO';
export  const   VALIDAR_FORMULARIO_ERROR  =   'VALIDAR_FORMULARIO_ERROR';

export  const   AGREGAR_SOLICITUD  =   'AGREGAR_SOLICITUD';
export  const   AGREGAR_SOLICITUD_EXITO  =   'AGREGAR_SOLICITUD_EXITO';
export  const   AGREGAR_SOLICITUD_ERROR  =   'AGREGAR_SOLICITUD_ERROR';

export const    COMENZAR_DESCARGA_SOLICITUDES =   'COMENZAR_DESCARGA_SOLICITUDES';
export const    DESCARGA_SOLICITUDES_EXITO =   'DESCARGA_SOLICITUDES_EXITO';
export const    DESCARGA_SOLICITUDES_ERROR =   'DESCARGA_SOLICITUDES_ERROR';

export const    OBTENER_SOLICITUD_ELIMINAR =   'OBTENER_SOLICITUD_ELIMINAR';
export const    ELIMINAR_SOLICITUD_EXITO =   'ELIMINAR_SOLICITUD_EXITO';
export const    ELIMINAR_SOLICITUD_ERROR =   'ELIMINAR_SOLICITUD_ERROR';

export const    OBTENER_SOLICITUD_EDITAR =   'OBTENER_SOLICITUD_EDITAR';
export const    SOLICITUD_EDITAR_EXITO =   'SOLICITUD_EDITAR_EXITO';
export const    SOLICITUD_EDITAR_ERROR =   'SOLICITUD_EDITAR_ERROR';

export const    COMENZAR_EDICION_SOLICITUD =   'COMENZAR_EDICION_SOLICITUD';
export const    SOLICITUD_EDITADO_EXITO =   'SOLICITUD_EDITADO_EXITO';
export const    SOLICITUD_EDITADO_ERROR =   'SOLICITUD_EDITADO_ERROR';

export const    COMENZAR_CREAR_CLIENTE =   'COMENZAR_CREAR_CLIENTE';
export const    CREAR_CLIENTE_EXITO =   'CREAR_CLIENTE_EXITO';
export const    CREAR_CLIENTE_ERROR =   'CREAR_CLIENTE_ERROR';

export const    OBTENER_CLIENTES =   'OBTENER_CLIENTES';
export const    OBTENER_CLIENTES_EXITO =   'OBTENER_CLIENTES_EXITO';
export const    OBTENER_CLIENTES_ERROR =   'OBTENER_CLIENTES_ERROR';

export const    OBTENER_DIVISION =   'OBTENER_DIVISION';
export const    OBTENER_DIVISION_EXITO =   'OBTENER_DIVISION_EXITO';
export const    OBTENER_DIVISION_ERROR =   'OBTENER_DIVISION_ERROR';

export const    OBTENER_SUCURSALES =   'OBTENER_SUCURSALES';
export const    OBTENER_SUCURSALES_EXITO =   'OBTENER_SUCURSALES_EXITO';
export const    OBTENER_SUCURSALES_ERROR =   'OBTENER_SUCURSALES_ERROR';

export const    OBTENER_PROVEEDORES =   'OBTENER_PROVEEDORES';
export const    OBTENER_PROVEEDORES_EXITO =   'OBTENER_PROVEEDORES_EXITO';
export const    OBTENER_PROVEEDORES_ERROR =   'OBTENER_PROVEEDORES_ERROR';

export const    OBTENER_CLASE_PEDIDO =   'OBTENER_CLASE_PEDIDO';
export const    OBTENER_CLASE_PEDIDO_EXITO =   'OBTENER_CLASE_PEDIDO_EXITO';
export const    OBTENER_CLASE_PEDIDO_ERROR =   'OBTENER_CLASE_PEDIDO_ERROR';

export const    OBTENER_EMBARQUES =   'OBTENER_EMBARQUES';
export const    OBTENER_EMBARQUES_EXITO =   'OBTENER_EMBARQUES_EXITO';
export const    OBTENER_EMBARQUES_ERROR =   'OBTENER_EMBARQUES_ERROR';

export const    OBTENER_DESTINOS =   'OBTENER_DESTINOS';
export const    OBTENER_DESTINOS_EXITO =   'OBTENER_DESTINOS_EXITO';
export const    OBTENER_DESTINOS_ERROR =   'OBTENER_DESTINOS_ERROR';

export const    OBTENER_TIPO_PRODUCTO =   'OBTENER_TIPO_PRODUCTO';
export const    OBTENER_TIPO_PRODUCTO_EXITO =   'OBTENER_TIPO_PRODUCTO_EXITO';
export const    OBTENER_TIPO_PRODUCTO_ERROR =   'OBTENER_TIPO_PRODUCTO_ERROR';

export const    OBTENER_MONEDAS =   'OBTENER_MONEDAS';
export const    OBTENER_MONEDAS_EXITO =   'OBTENER_MONEDAS_EXITO';
export const    OBTENER_MONEDAS_ERROR =   'OBTENER_MONEDAS_ERROR';

export const    OBTENER_PRODUCTOS_EXCEL =   'OBTENER_PRODUCTOS_EXCEL';
export const    OBTENER_PRODUCTOS_EXCEL_EXITO =   'OBTENER_PRODUCTOS_EXCEL_EXITO';
export const    OBTENER_PRODUCTOS_EXCEL_ERROR =   'OBTENER_PRODUCTOS_EXCEL_ERROR';

export  const   AGREGAR_PRODUCTO  =   'AGREGAR_PRODUCTO';
export  const   AGREGAR_PRODUCTO_EXITO  =   'AGREGAR_PRODUCTO_EXITO';
export  const   AGREGAR_PRODUCTO_ERROR  =   'AGREGAR_PRODUCTO_ERROR';

export const    OBTENER_PRODUCTOS_SOLICITUD =   'OBTENER_PRODUCTOS_SOLICITUD';
export const    OBTENER_PRODUCTOS_SOLICITUD_EXITO =   'OBTENER_PRODUCTOS_SOLICITUD_EXITO';
export const    OBTENER_PRODUCTOS_SOLICITUD_ERROR =   'OBTENER_PRODUCTOS_SOLICITUD_ERROR';

export  const   ELIMINAR_PRODUCTO  =   'ELIMINAR_PRODUCTO';
export  const   ELIMINAR_PRODUCTO_EXITO  =   'ELIMINAR_PRODUCTO_EXITO';
export  const   ELIMINAR_PRODUCTO_EDITAR_EXITO  =   'ELIMINAR_PRODUCTO_EDITAR_EXITO';
export  const   ELIMINAR_PRODUCTO_ERROR  =   'ELIMINAR_PRODUCTO_ERROR';